import type { Metadata } from "next";
import "./globals.css";
import { WindowsProvider } from "@/src/window";

export const metadata: Metadata = {
  title: "Vitoshkin Kirill Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-full h-dvh">
        <WindowsProvider>{children}</WindowsProvider>
      </body>
    </html>
  );
}
